### ISSUE TITLE
how to incorporate with templates 

### ISSUE THREAD

**Issue by Svyk** [8bitgentleman/roam-depot-block-self-destruct#1]
how would I incorporate with templates or smart block button? 

Like if I don't click a smart block button I want it deleted, but I don't want to tag every single time. It would be nice to add a self destruct on a template but the template itself doesn't get deleted. if that makes sense

**Comment by 8bitgentleman** [comment]
I'm not sure I follow your question but the extension is set up to ignore blocks that are a part of either native roam templates (roam/templates) and/or SmartBlocks. Once the template is used then the self-destruct timer starts so to speak. Does that answer your question?

**Comment by Svyk** [comment]
> I'm not sure I follow your question but the extension is set up to ignore blocks that are a part of either native roam templates (roam/templates) and/or SmartBlocks. Once the template is used then the self-destruct timer starts so to speak. Does that answer your question?

yes!! Sorry I did not know this. What a great plugin to keep daily notes page very clean. I've been taking the time to retroactively add it to every query ....there's a lot.  Thanks for making this!!
