### ISSUE TITLE
Suggestion: Add sentence that templates and SBs are excluded

### ISSUE THREAD

**Issue by kvistgaard** [8bitgentleman/roam-depot-block-self-destruct#2]
I believe that adding such a sentence in the documentation will increase the utilisation of the extension.

**Comment by 8bitgentleman** [comment]
This is already mentioned in the first paragraph of the docs. 
> ![image](https://github.com/user-attachments/assets/cb647a20-48e7-4faf-8f74-3537f68ab124)

Are you suggesting some change here to make it more clear?

**Comment by kvistgaard** [comment]
Doesn't show up in Roam

**Comment by 8bitgentleman** [comment]
This should show up in Roam now with the latest version. If you have other copy suggestions feel free to open another issue
